/* eslint-disable */
// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export function Routes(searchParams) {
  const query = searchParams ? '?' + new URLSearchParams(searchParams).toString() : '';
  return {
    index: `/${query}` ,
    _404: (_404) => ({index: `/${_404}${query}`}),
    routeSlash: {index: `/route-slash${query}`},
    about: {index: `/about${query}`},
    api: {
      test: {index: `/api/test${query}`},
    },
    auth: {
      abc: {index: `/auth/abc${query}`},
    },
    posts: {
      index: `/posts${query}`,
      slug: (slug) => ({index: `/posts/${slug}${query}`}),
      t: {index: `/posts/t${query}`},
      z: {index: `/posts/z${query}`},
      ooo: {
        index: `/posts/ooo${query}`,
        p: {index: `/posts/ooo/p${query}`},
        optional: (optional) => ({
          index: `/posts/ooo${optional ? `/${optional}` : ''}${query}`,
          test: {index: `/posts/ooo${optional ? `/${optional}` : ''}/test${query}`},
        }),
      },
    },
    multiple: {
      third: (third) => ({
        edit: {index: `/multiple/${third}/edit${query}`},
      }),
      first: (first) => ({
        second: (second) => ({
          third: (third) => ({index: `/multiple/${first}/${second}/${third}${query}`}),
        }),
      }),
    },
    manifestJson: {index: `/manifest.json${query}`},
  };
}