// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export declare function routes(searchParams?:Record<string, string>):{
    index: string;
    _404: (_404:string|number) => ({index: string});
    about: {index: string};
    posts: {
      index: string;
      t: {index: string};
      z: {index: string};
      ooo: {
        index: string;
        p: {index: string};
        optional: (optional?:string|number) => ({
          index: string;
          test: {index: string};
        });
      };
      slug: (slug:string|number) => ({index: string});
    };
    auth: {
      abc: {index: string};
    };
    routeSlash: {index: string};
    manifestJson: {index: string};
    multiple: {
      third: (third:string|number) => ({
        edit: {index: string};
      });
      first: (first:string|number) => ({
        second: (second:string|number) => ({
          third: (third:string|number) => ({index: string});
        });
      });
    };
};