// This file is generated by the routeManifestPlugin. Do not edit manually.
export const Routes = {
  about: '/about',
  auth: { test: '/auth/test' },
  posts: { ':posts': '/posts/:slug' },
  multiple: new Proxy(
    {},
    {
      get: (target, prop) => {
        return `/${String(prop)}`;
      },
    },
  ),
};

export type RoutePaths = keyof typeof Routes;
