// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export declare function Routes(searchParams?:Record<string, string>):{
    index: string;
    multiple: {
      first: (first:string|number) => ({
        second: (second:string|number) => ({
          third: (third:string|number) => ({index: string});
        });
      });
      third: (third:string|number) => ({
        edit: {index: string};
      });
    };
    posts: {
     index: string;
      ooo: {
        slug: (slug:string|number) => ({index: string});
        p: {index: string};
      };
      z: {index: string};
    };
    auth: {
      abc: {index: string};
    };
    api: {
      test: {index: string};
    };
    about: {index: string};
    _404: {index: string};
};