// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export function Routes(searchParams) {
  const query = searchParams ? '?' + new URLSearchParams(searchParams).toString() : '';
  return {
    index: `/${query}` ,
    multiple: {
      first: (first) => ({
        second: (second) => ({
          third: (third) => ({index: `/multiple/${first}/${second}/${third}${query}`}),
        }),
      }),
      third: (third) => ({
      }),
    },
    posts: {
     index: `/posts${query}`,
      ooo: {
        slug: (slug) => ({index: `/posts/ooo/${slug}${query}`}),
      },
    },
    auth: {
    },
    api: {
    },
  };
}