// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export function Routes(searchParams) {
  const query = searchParams ? '?' + new URLSearchParams(searchParams).toString() : '';
  return {
    index: `/${query}` ,
    multiple: {
      first: (first) => ({
        second: (second) => ({
          third: (third) => ({index: `/multiple/${first}/${second}/${third}${query}`}),
        }),
      }),
      third: (third) => ({
        edit: {index: `/multiple/${third}/edit${query}`},
      }),
    },
    posts: {
     index: `/posts${query}`,
      ooo: {
        slug: (slug) => ({index: `/posts/ooo/${slug}${query}`}),
        p: {index: `/posts/ooo/p${query}`},
      },
      z: {index: `/posts/z${query}`},
    },
    auth: {
      abc: {index: `/auth/abc${query}`},
    },
    api: {
      test: {index: `/api/test${query}`},
    },
    about: {index: `/about${query}`},
    _404: {index: `/_404${query}`},
  };
}