// ################################################
// ### THIS FILE IS AUTOGENERATED - DO NOT EDIT ###
// ################################################
export declare function Routes(searchParams?:Record<string, string>):{
    index: string;
    multiple: {
      first: (first:string|number) => ({
        second: (second:string|number) => ({
          third: (third:string|number) => ({index: string});
        });
      });
      third: (third:string|number) => ({
      });
    };
    posts: {
     index: string;
      ooo: {
        slug: (slug:string|number) => ({index: string});
      };
    };
    auth: {
    };
    api: {
    };
};