name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - name: Install
        run: pnpm ci

      - name: Build
        run: pnpm build

      # Check the version and publish the package
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm publish

